logging:
  level:
    ROOT: DEBUG
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telegram?currentSchema=dev
    username: postgres
    password: postgres
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
feign:
  client:
    config:
      auth:
        logger-level: FULL
#feign:
#  client:
#    gpt:
#      listOfServers: "http://192.168.2.68:3040"
#    config:
#      default:
#        loggerLevel: full